# Generated by Django 5.1 on 2024-09-02 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_sendnotification"),
    ]

    operations = [
        migrations.CreateModel(
            name="SendNotificationProxy",
            fields=[],
            options={
                "verbose_name": "Unsend Notification",
                "verbose_name_plural": "Unsend Notifications",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.sendnotification",),
        ),
        migrations.AlterField(
            model_name="sendnotification",
            name="email",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="send_notification",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
